### ISSUE TITLE
怎样下载你的测试数据集？

### ISSUE THREAD

**Issue by chenloveheimei** [Zeqiang-Lai/HSI-RefSR#1]
1.我点击你的测试数据集的链接，跳转到hugging face那个网站，但git clone 报错‘
git clone https://huggingface.co/datasets/aaronb/HSI-RefSR
正克隆到 'HSI-RefSR'...
fatal: 无法访问 'https://huggingface.co/datasets/aaronb/HSI-RefSR/'：gnutls_handshake() failed: Error in the pull function.

谢谢。

**Comment by Zeqiang-Lai** [comment]
onedrive：

https://1drv.ms/u/s!AuS3o7sEiuJnmGsd7XtzN9ekPXt6?e=NeAExF
