### ISSUE TITLE
关于光流估计的问题

### ISSUE THREAD

**Issue by chenzean** [Zeqiang-Lai/HSI-RefSR#2]
作者，你好。我看您再论文中使用了简单的卷积层来估计光流。而我使用您写的估计网络的网络和warping代码，但是估计不出来光流（估计出来的结果更像图像的纹理图）。想问一下作者，这是中间有什么遗漏了吗？（将warping后的图像和GT值计算损失）

**Comment by Zeqiang-Lai** [comment]
卷积层应该是说全卷积的 flownet ？具体的光流图是什么样的呢？

**Comment by chenzean** [comment]
我在阅读了您写的代码进行了修改。变成了普通的卷积神经网络。例如：
![1](https://github.com/Zeqiang-Lai/HSI-RefSR/assets/107561504/50cfe9f4-c1dc-42f8-a806-a1b535bb98b1)
通过warping后的结果和GT计算损失。
下图是图像：
![3](https://github.com/Zeqiang-Lai/HSI-RefSR/assets/107561504/10614146-9e02-4652-96bb-1f732b42676b)
最后的估计出来的结果如下所示：
![2](https://github.com/Zeqiang-Lai/HSI-RefSR/assets/107561504/c92d3685-e0d9-4c50-bf75-b7577e818036)

**Comment by Zeqiang-Lai** [comment]
我这边 flownet 的设定是和超分从零开始联合训练的，所以光流估计的能力是隐式学习到的，所以flownet 的效果取决于数据集质量，数据集如果是 light-field 那种数据集，那应该可以得到不错的光流图。如果数据集比较小，那训出来质量可能比较差。

**Comment by chenzean** [comment]
我这边正好就是光场图像。 我想问一下您那边计算光流的约束是什么？L1损失吗？发自我的 iPhone在 2023年11月28日，20:06，Zeqiang Lai ***@***.***> 写道：﻿
我这边 flownet 的设定是和超分从零开始联合训练的，所以光流估计的能力是隐式学习到的，所以flownet 的效果取决于数据集质量，数据集如果是 light-field 那种数据集，那应该可以得到不错的光流图。如果数据集比较小，那训出来质量可能比较差。

**Comment by Zeqiang-Lai** [comment]
隐式监督，不会直接在光流上算 loss，因为我的数据集没有光流的GT，loss 是在最后的超分图像上算的，用的 SmoothL1Loss

**Comment by chenzean** [comment]
哦哦哦好滴谢谢啦发自我的 iPhone在 2023年11月28日，20:11，Zeqiang Lai ***@***.***> 写道：﻿
隐式监督，不会直接在光流上算 loss，因为我的数据集没有光流的GT，loss 是在最后的超分图像上算的，用的 SmoothL1Loss
